# Generated by Django 5.2.6 on 2025-09-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymembership',
            name='name',
            field=models.CharField(default='Pepe Perez', max_length=255),
        ),
    ]
