# Generated by Django 5.2.6 on 2025-09-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymembership',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
